### PR TITLE
editable component

### PR DESCRIPTION
**Pull request by GamerGirlandCo**
this lays the groundwork for textual editing in most views.
as always, let me know if there's anything i can change or improve :)

you can toggle editing on most of these components by double clicking, while some (like the rating) are editable by default

### CODE REVIEW

**Comment by blacksmithgu** [comment]
How does contenteditable actually feel in your experience for text, as compared to a `textarea`? I'm a bit worried that they can be fragile without really heavyweight libraries behind them.

**Comment by GamerGirlandCo** [comment]
> How does contenteditable actually feel in your experience for text, as compared to a `textarea`? I'm a bit worried that they can be fragile without really heavyweight libraries behind them.

i'm inclined to agree about them being fragile, but so long as we stick to plain text, everything *should* be fine.

(though at that point, if there's only plain text, you have a point -- just use a textarea lol)

**Comment by blacksmithgu** [comment]
I've messed with the CSS a bit here and swapped to using `import "blah.css"` imports so it's now possible to split CSS into multiple files. I think moving the editable component styles into it's own CSS file should fix this.

**Comment by GamerGirlandCo** [comment]
> I've messed with the CSS a bit here and swapped to using `import "blah.css"` imports so it's now possible to split CSS into multiple files. I think moving the editable component styles into it's own CSS file should fix this.

done!

**Comment by blacksmithgu** [comment]
Are you at a point where you would be comfortable merging this? I tend to like avoiding super-long lived branches and would rather we merged things that work and then fix them up extend them in further PRs as long as you are alright with the existing logic.

**Comment by blacksmithgu** [comment]
Broadly the logic that I've seen seems fine to me, though I haven't actually run it locally yet.

**Comment by GamerGirlandCo** [comment]
> Are you at a point where you would be comfortable merging this? I tend to like avoiding super-long lived branches and would rather we merged things that work and then fix them up extend them in further PRs as long as you are alright with the existing logic.

yes, i'd say so. i've ran the plugin with these changes locally, and everything works as it should for me

**Review by blacksmithgu — APPROVED** [review]

**Pull request merged**
