### PR TITLE
feat: support some useful components for basic ui

### PR DESCRIPTION
**Pull request by Quorafind**
- [x] Checkbox
- [x] Slider
- [x] Switch
- [x] Select 
- [x] Icon

### CODE REVIEW

**Comment by Quorafind** [comment]
Clip_2024-06-20_23-40-22

**Comment by blacksmithgu** [comment]
Checking this out locally now!

**Comment by Quorafind** [comment]
You can try this via 
````
```datacorejsx
return function View() {
    return <>
    <dc.Group justify="start">
                <dc.Checkbox />
                <dc.Stack justify="center">
                    <dc.Slider max={10} min={1} steps={2} />
                </dc.Stack>
                <dc.Stack justify="center">
                    <dc.Switch />
                </dc.Stack>
                <dc.Icon icon={"x"} />
	          <dc.VanillaSelect options={[{value: "new", label: "new"},{value: "old", label:"old"}]} defaultValue={"new"} />
            </dc.Group>
    </>

}

```
````

**Review by blacksmithgu — APPROVED** [review]

**Comment by blacksmithgu** [comment]
Looks great!

**Pull request merged**
